### ISSUE TITLE
typo ''Possion" instead of "Poisson"

### ISSUE THREAD

**Issue by SelimRaboudi** [yanyachen/MLmetrics#1]
Hey Yachen,

Nice work with MLmetrics :)
I noticed a typo in your CRAN documentation, you write "Possion" instead of "Poisson"

Regards,

Selim

**Comment by yanyachen** [comment]
Hi Selim, 

I have fixed the typo, thank you
I have updated the package from v1.1.0 to v1.1.1
You can download the github version for now
I will submit to CRAN one week later, because I have submitted 3 different packages this week
BTW, Love your work on Vowpal Wabbit in R

Best,

Yachen

**Comment by yanyachen** [comment]
The CRAN Version has also been updated to v1.1.1
Closing issue.
Thank you very much for that.
